### ISSUE TITLE
Add OpenTelemetry support

### ISSUE THREAD

**Issue by pquentin** [elastic/elasticsearch-serverless-python#52]
Based on the OpenTelemetry work made in the client itself.

Here are the pull requests to backport:

- [x] https://github.com/elastic/elasticsearch-py/pull/2457
- [x] https://github.com/elastic/elasticsearch-py/pull/2466 
- [x] https://github.com/elastic/elasticsearch-py/pull/2470
- [x] https://github.com/elastic/elasticsearch-py/pull/2479
- [x] https://github.com/elastic/elasticsearch-py/pull/2482
- [x] https://github.com/elastic/elasticsearch-py/pull/2490
- [x] https://github.com/elastic/elasticsearch-py/pull/2491

Done with those pull requests:

 * https://github.com/elastic/elasticsearch-serverless-python/pull/69
 * https://github.com/elastic/elasticsearch-serverless-python/pull/70
